--add your custom voicelines to sm64coopdx by adding the .ogg file to the sound folder and adding the file name to the CUSTOM_VOICETABLE table
--example: [CHAR_SOUND_OKEY_DOKEY] = 'your file.ogg',--Selecting a Character
_G.CUSTOM_VOICETABLE = {
    [CHAR_SOUND_OKEY_DOKEY] = '',--Selecting a Character
    [CHAR_SOUND_LETS_A_GO] = '',--Starting a level
    [CHAR_SOUND_PUNCH_YAH] = '',--first punch line
    [CHAR_SOUND_PUNCH_WAH] = '',--second punch line
    [CHAR_SOUND_WAH2] = '',--Throwing a heavy object
    [CHAR_SOUND_PUNCH_HOO] = '',--Kick line
    [CHAR_SOUND_YAH_WAH_HOO] = '',--first jump line (For VAs, You must do a YAH sound, a WAH sound and a HOO sound, seperated in their own file)
    [CHAR_SOUND_HOOHOO] = '',--second jump line
    [CHAR_SOUND_YAHOO_WAHA_YIPPEE] = '',--triple jump line (For VAs, You must do a YAHOO sound, a WAHA sound and a YIPEE sound, seperated in their own file)
    [CHAR_SOUND_UH] = '',--Failing a wallkick/grabbing a ledge
    [CHAR_SOUND_UH2] = '',--Jumping up a ledge (pressing A)
    [CHAR_SOUND_UH2_2] = '',--landing a long jump
    [CHAR_SOUND_HAHA] = '',--posing after backwards jump
    [CHAR_SOUND_YAHOO] = '',--Long jump
    [CHAR_SOUND_DOH] = '', --bouncing against a wall when long jump or diving
    [CHAR_SOUND_WHOA] = '',--Grabbing a ledge
    [CHAR_SOUND_EEUH] = '',--climbing a ledge slowly (pressign up)
    [CHAR_SOUND_WAAAOOOW] = '',--Mario falling a great height
    [CHAR_SOUND_TWIRL_BOUNCE] = '',--When bouncing on an enemy that makes mario spin jump
    [CHAR_SOUND_GROUND_POUND_WAH] = '',--used when Mario finishes his ground pound animation (his flip) and descends, not when he lands or when the button is pressed
    [CHAR_SOUND_HRMM] = '',--Grabbing something heavy (king bob omb for example)
    [CHAR_SOUND_HERE_WE_GO] = '',--Putting a power up cap on or a star
    [CHAR_SOUND_SO_LONGA_BOWSER] = '',--Mario throwing Bowser
    [CHAR_SOUND_OOOF] = '',--being pushed by a bully
    [CHAR_SOUND_OOOF2] = '',--landing after bouncing against a wall, landing after being ejected from a painting
    [CHAR_SOUND_ATTACKED] = '',--Mario being hit
    [CHAR_SOUND_PANTING] = '',--low hp idle line
    [CHAR_SOUND_PANTING_COLD] = '',--instead of sleeping, mario shivers in a cold level
    [CHAR_SOUND_ON_FIRE] = '',--Mario getting hit by a fire attack and running around on fire
    [CHAR_SOUND_SNORING1] = '',--Mario snoring when the sleeping anim is left too long
    [CHAR_SOUND_SNORING2] = '',--Mario snoring when the sleeping anim is left too long
	[CHAR_SOUND_SNORING3] = '',--Mario sleeping and thinking of italian dishes (first two in the array are snoring1 and 2, third one is the pasta dream)
	[CHAR_SOUND_COUGHING1] = '',--hazy maze cave gas makes mario coughs
	[CHAR_SOUND_COUGHING2] = '',--hazy maze cave gas makes mario coughs
	[CHAR_SOUND_COUGHING3] = '',--hazy maze cave gas makes mario coughs
	[CHAR_SOUND_DROWNING] = '',--dying underwater
	[CHAR_SOUND_DYING]	= '',--Mario dying in most circumstances
	[CHAR_SOUND_IMA_TIRED] = '',--Mario when idle too long, just before starting to doze off
	[CHAR_SOUND_YAWNING] = '',--Mario yawning before starting his dozing anim
	[CHAR_SOUND_MAMA_MIA] = '',--When mario is ejected from a painting when losing a life, they say this line
}